print("請輸入x1的座標")
x1 = input()
x1 = float(x1)
print("請輸入y1的座標")
y1 = input()
y1 = float(y1)
print("請輸入x2的座標")
x2 = input()
x2 = float(x2)
print("請輸入y2的座標")
y2 = input()
y2 = float(y2)
dist = ((x2 - x1) ** 2 + (y2 - y1) ** 2)**0.5
print("兩點距離為")
print(dist)